### ISSUE TITLE
Frontend issues:

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#1]
1) Have to fix the JS on delete functionality

**Comment by cup** [comment]
This seems to still be broken - if you delete a file it still shows on user page

**Comment by mayeaux** [comment]
Thanks for pointing that out, I think I can fix that right now.

**Comment by mayeaux** [comment]
Okay that should be fixed with this commit: https://github.com/mayeaux/nodetube/commit/04bc4207a9e12cff7e3d03e155faeefb965327e7

Thanks for letting me know!
