### ISSUE TITLE
TypeError: fs.copyFile is not a function when build on Heroku

### ISSUE THREAD

**Issue by psunjohnny** [mayeaux/nodetube#101]
Heroku build output:      

       > node ./scripts/download.js
       
       Downloaded youtube-dl 2020.01.01
       
       > NodeTube@1.0.0 postinstall /tmp/build_1a3dfca4bec3422176e286462dc2d57a
       > node ./postinstall.js
       
       /tmp/build_1a3dfca4bec3422176e286462dc2d57a/postinstall.js:4
       fs.copyFile('.env.settings.sample', '.env.settings', { flag: "wx" }, (err) => {
          ^
       
       TypeError: fs.copyFile is not a function
           at Object.<anonymous> (/tmp/build_1a3dfca4bec3422176e286462dc2d57a/postinstall.js:4:4)
           at Module._compile (module.js:573:30)
           at Object.Module._extensions..js (module.js:584:10)
           at Module.load (module.js:507:32)
           at tryModuleLoad (module.js:470:12)
           at Function.Module._load (module.js:462:3)
           at Function.Module.runMain (module.js:609:10)
           at startup (bootstrap_node.js:158:16)
           at bootstrap_node.js:578:3
       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! NodeTube@1.0.0 postinstall: `node ./postinstall.js`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the NodeTube@1.0.0 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.mraWE/_logs/2020-01-07T06_30_38_574Z-debug.log
       -----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
      !     Push rejected, failed to compile Node.js app.
      !     Push failed

**Comment by psunjohnny** [comment]
> Heroku build output:
> 
> ```
>    > node ./scripts/download.js
>    
>    Downloaded youtube-dl 2020.01.01
>    
>    > NodeTube@1.0.0 postinstall /tmp/build_1a3dfca4bec3422176e286462dc2d57a
>    > node ./postinstall.js
>    
>    /tmp/build_1a3dfca4bec3422176e286462dc2d57a/postinstall.js:4
>    fs.copyFile('.env.settings.sample', '.env.settings', { flag: "wx" }, (err) => {
>       ^
>    
>    TypeError: fs.copyFile is not a function
>        at Object.<anonymous> (/tmp/build_1a3dfca4bec3422176e286462dc2d57a/postinstall.js:4:4)
>        at Module._compile (module.js:573:30)
>        at Object.Module._extensions..js (module.js:584:10)
>        at Module.load (module.js:507:32)
>        at tryModuleLoad (module.js:470:12)
>        at Function.Module._load (module.js:462:3)
>        at Function.Module.runMain (module.js:609:10)
>        at startup (bootstrap_node.js:158:16)
>        at bootstrap_node.js:578:3
>    npm ERR! code ELIFECYCLE
>    npm ERR! errno 1
>    npm ERR! NodeTube@1.0.0 postinstall: `node ./postinstall.js`
>    npm ERR! Exit status 1
>    npm ERR! 
>    npm ERR! Failed at the NodeTube@1.0.0 postinstall script.
>    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>    
>    npm ERR! A complete log of this run can be found in:
>    npm ERR!     /tmp/npmcache.mraWE/_logs/2020-01-07T06_30_38_574Z-debug.log
>    -----> Build failed
>    
>    We're sorry this build is failing! You can troubleshoot common issues here:
>    https://devcenter.heroku.com/articles/troubleshooting-node-deploys
>    
>    If you're stuck, please submit a ticket so we can help:
>    https://help.heroku.com/
>    
>    Love,
>    Heroku
> ```
> 
> ! Push rejected, failed to compile Node.js app.
> ! Push failed

**Comment by RossComputerGuy** [comment]
Node.JS version?

**Comment by mayeaux** [comment]
Thanks for letting me know, apparently fs.copyFile doesn't land until Node 8.5 and I was running Node 8.2. Latest master should have a fix let me know if that works for you, thanks!

**Comment by psunjohnny** [comment]
Thank you for the quick action.
