### ISSUE TITLE
Plyr somewhat buggy, doesn't show the sound button at times

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#129]
![Screen Shot 2020-01-25 at 3 02 06 PM](https://user-images.githubusercontent.com/7200471/73127840-b64d3400-3f83-11ea-893d-6406e353b70e.png)

This is pretty annoying, not sure what's going on. @Ryochan7 is this a 'feature' in the current plyr setup? The whole thing is a bit odd

**Comment by Ryochan7** [comment]
Found an issue talking about this problem. Plyr adds the hidden attribute to that block for some reason. The issue even affects the latest release of Plyr (3.5.6). One workaround that was mentioned in the thread that works is to add `preload="none"` to the video tag.

https://github.com/sampotts/plyr/issues/1219

**Comment by sampotts** [comment]
If you upgrade to the latest version of the Plyr this will be resolved, it was resolved a few versions ago.

**Comment by mayeaux** [comment]
Perfect ty!

**Comment by mayeaux** [comment]
This is fixed now
