### ISSUE TITLE
Preserve upload rotation

### ISSUE THREAD

**Issue by RossComputerGuy** [mayeaux/nodetube#144]
If someone submits a portrait image, NodeTube should make sure its not rotated.

**Comment by RossComputerGuy** [comment]
[Example](https://nodetube.live/user/TheComputerGuy/pnKOLiW)

**Comment by mayeaux** [comment]
This is what's going on: https://stackoverflow.com/questions/24658365/img-tag-displays-wrong-orientation

**Comment by RossComputerGuy** [comment]
Adding `image-orientation: from-image;` to the image should fix it.

**Comment by Danissss** [comment]
Hi, what is the status on this issue? Where should I add this property?

**Comment by mayeaux** [comment]
@Danissss , thanks for your interest, as it turns out the browser support for this feature is very sparse. I will close this issue in the meantime as it looks like we're still some ways away from this landing in a decent amount of browsers.

https://caniuse.com/#feat=css-image-orientation
