### ISSUE TITLE
Upload from clipboard

### ISSUE THREAD

**Issue by RossComputerGuy** [mayeaux/nodetube#145]
Discord has this feature where you can push Ctrl-v or right click on the text box and click paste which then pastes the file or whatever is in the clipboard. This should work on Nodetube as well.

**Comment by mayeaux** [comment]
Functionality is here if anyone wants to add it: https://stackoverflow.com/questions/50427513/html-paste-clipboard-image-to-file-input

**Comment by Mxchaeltrxn** [comment]
Hey I can take this issue on. 

Questions:
Where should this pasting functionality be allowed?

**Comment by mayeaux** [comment]
Hey thanks for the message, I'm just finishing up something but if you want to check out `views/uploading.pug` in the meantime I can give you the full rundown in ~20 min, thanks again!

**Comment by mayeaux** [comment]
Yeah exactly I forgot Resumable handled the frontend logic. On the latest master if you check here:
`views/uploading.pug:301` you'll see we'd have to rig a workaround via assignBrowse or assignDrop so it's a bit tougher. I don't see any custom assignment functions here: 
http://www.resumablejs.com/

So yeah this will end up being a bit more complex than originally thought but it shouldn't be impossible to rig something up with assignDrop or assignBrowse I'm guessing it will just take some tinkering around.

**Comment by mayeaux** [comment]
Actually I think you can just do a workaround. If you're able to join us on Discord that will be helpful because it's a bit more sync than Github comments. https://nodetube.live/discord if you're able

**Comment by mayeaux** [comment]
Actually to do it, basically get that file from the clipboard and then add it manually, see this here:

https://github.com/23/resumable.js/issues/414

**Comment by Mxchaeltrxn** [comment]
@RossComputerGuy So I've tried to implement this feature but I can't find a way to do it on browser. 

I have found ways to get this to work with drag and drop and with images but have not found a way to get it to work with videos. I'm not sure if it's possible either on browser (can you think of any examples of sites that allow this?). Do you have any suggestions on the implementation of this feature?

**Comment by RossComputerGuy** [comment]
Copying videos is near impossible because of the size, it has to copy the entire file into the clipboard which would fill up memory.

**Comment by mayeaux** [comment]
Looks like maybe it can be done through File System API: https://stackoverflow.com/a/38254151/3973137

**Comment by mayeaux** [comment]
It doesn't look possible, I'm closing this.
