### ISSUE TITLE
Duration for audio/video files

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#160]
Can add a durationInSeconds field to the Upload model. 

Can use ffmpeg (check out the ffprobe functionality at controllers/backend/uploading.js:370 I think it should be there) to get the values, and then save it to the document during the upload process.

**Comment by Mxchaeltrxn** [comment]
I can do this

**Comment by mayeaux** [comment]
Merged, nicely done @Mxchaeltrxn !
