### ISSUE TITLE
Period in the title breaks the upload

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#165]
It looks like having a period in the filename breaks the upload functionality. 

I haven't tested it a bunch but that's what it looks like at first glance

**Comment by Mxchaeltrxn** [comment]
@mayeaux I'm unable to replicate this. The file name I used was this: '1 Second .Video-Wch3gJG2GJ4' without the quotation marks and it was successful locally.

**Comment by mayeaux** [comment]
Sorry, I implemented the fix just on another computer. It was unrelated to the title meant to get around to this earlier but didn't have a chance. I'll get that fix pushed tomorrow.
