### ISSUE TITLE
Show file duration on thumbnail for videos and audio files

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#175]
It's very useful for a user to know how long (in duration) a video/audio file is before they click on a piece of content. We should display this on the frontend, either with the rest of the upload details or perhaps even on the thumbnail in similar fashion to YouTube.

**Comment by iddev5** [comment]
Cool and useful. But as you said "rest of the upload details" I was wondering if it's even possible to use something different from the YouTube's style and still get the same result on every platform.

**Comment by mayeaux** [comment]
Explain that more @iddev5 ?

**Comment by iddev5** [comment]
I don't have anything to explain. Right now, the way YouTube shows file duration is the only mode. I was wondering if some other way is possible.

Information in text form below the thumbnail is definitely an option but it might look a bit weird.
