### ISSUE TITLE
Update node source to 12.0

### ISSUE THREAD

**Issue by coronad0** [mayeaux/nodetube#184]
Update on linux ubuntu instructions:

curl -sL https://deb.nodesource.com/setup_8.x

to setup_12.x

**Comment by chovy** [comment]
I did this. you should be using nvm for node.

**Comment by mayeaux** [comment]
Thanks for the post @coronad0 . I have new Ubuntu installation instructions I'll be dropping into the Wiki soon which use nvm. Those will be coming out pretty soon. Did you manage to get the app booted locally for yourself?

**Comment by coronad0** [comment]
I did! Thanks a ton! Testing now and I'm fairly new to Node and while I'm up and running maybe full instructions on the Linux page to make it easier would help; e.g., followed the linux instructions and up and running, had no idea I needed to be on port 3000, didn't know I needed to npm install from the nodetube dir ... RTFM, I know, but putting it all on one page would be cool.

**Comment by mayeaux** [comment]
Yeah I just did an install on a fresh Ubuntu instance and saved all my commands so I'll go through and make it all look nice and replace the instructions when I have a chance, the current ones are a bit outdated/incomplete. And sweet lmk if you need help with anything!
