### ISSUE TITLE
Can't signup or login

### ISSUE THREAD

**Issue by forteller** [mayeaux/nodetube#195]
Hey. Thanks for creating this!

Just wanted to let you know that on the main node I'm not able to signup or login

I get these error messages after inputing username and password:

Cannot POST /signup

on the signup page and

Cannot POST /login

on the login page.

I tried on Nullvideo instead, and did not have the same problem there.

Firefox 74 on Ubuntu 19.10

Thanks again!

**Comment by mayeaux** [comment]
Thanks for the heads up, I see what's happening. Issue with my Mongodb instance (out of space).

**Comment by mayeaux** [comment]
This is fixed now btw, can you try again?
