### ISSUE TITLE
Subscribe button on mobile

### ISSUE THREAD

**Issue by carlostojal** [mayeaux/nodetube#200]
When not authenticated, when the subscribe button is pressed the popup appears and closes instantly. Tested on live instance newtube.app on Firefox, DuckDuckGo and Chrome. Haven't tested on desktop.

**Comment by mayeaux** [comment]
Thanks for letting me know, I think it could be related as well to: https://github.com/mayeaux/nodetube/issues/125

This would be a good candidate for the OSS community to check out

**Comment by carlostojal** [comment]
I checked and it's solved. Keep up the good work.

**Comment by carlostojal** [comment]
No, there's still the problem. If you press a little longer the popup doesn't close. It's just a split second until you start selecting the text.
