### ISSUE TITLE
NSFW or Sensitive content not possible to rate in UPLOAD page

### ISSUE THREAD

**Issue by deleteBigTech** [mayeaux/nodetube#249]
Only one rating available in upload page (on nullvideo.com)
![image](https://user-images.githubusercontent.com/64044709/79806547-8fbf4f00-8360-11ea-9e93-93fcaca76a9b.png)

If the content is not SFW, it has to be classified as SFW and then edited once uploaded (in edit mode there are the 3 possible ratings, but those should be shown on the upload page IMO, if and only if the instance host allows non-SFW content to be published)

Thanks!

**Comment by mayeaux** [comment]
Yeah this is an issue with the .env.settings file on nullvideo, not the code itself

Needs these lines added to .env.settings:

```
# level you want to allow, order from least to most controversial allowed [SFW,NSFW,SENS]
MAX_RATING_ALLOWED=SFW
``` 

@chovy  that should fix the problem
