### ISSUE TITLE
Update version of ffmpeg on newtube, recommend ffmpeg 3+

### ISSUE THREAD

**Issue by deleteBigTech** [mayeaux/nodetube#253]
**Original .mp4 video:**
https://1drv.ms/v/s!AlhdwNvcY7spgvY01ykAzC_pJZVAfA

**Uploaded .mp4 video** (temporary):
https://newtube.app/user/testing/7IcFEiV

**Display issues in the publish above (instances in time):**
00:42
01:03
01:13
01:37
02:28
03:11
04:11
05:05 (bottom of the display)
(basically this happens in almost all beginnings of power point slides - i used the power point export tool to make the video, but as you see the original video has no issues)

**.avi version published on newtube:**
https://newtube.app/user/fucksystem/5FtoBj1

**Comment by mayeaux** [comment]
Yeah this doesn't happen for me on OS X but does with Ubuntu so I'm guessing something is up with Ubuntu's version of ffmpeg. We'll see but that's what it looks like.

**Comment by mayeaux** [comment]
Was an old version of ffmpeg, this is the long-term fix: https://github.com/mayeaux/nodetube/issues/255
