### ISSUE TITLE
Title unchanged when new file is uploaded

### ISSUE THREAD

**Issue by deleteBigTech** [mayeaux/nodetube#256]
**Not sure if its on purpose**, but i would expect each uploaded file to automatically insert the file name as the content title. 

If you upload the first file, all goes good! But then if you realize the file is not the one you want and upload another file with a different name, the title is not updated - in order to get the title updated you need to delete the previous title first.

**Comment by mayeaux** [comment]
Yeah it's on purpose so that someone won't write a title and have it overwritten. Good spot though.
