### ISSUE TITLE
Nodetube's grey background

### ISSUE THREAD

**Issue by deleteBigTech** [mayeaux/nodetube#263]
Hi

**just to know if its on purpose** that the background of nodetube is not plain white, making plain white backgrounds (e.g, emojies + audio boxes, non-PNG pics) to contrast with nodetube's color.

**Examples:**

![image](https://user-images.githubusercontent.com/64044709/80319466-334cab80-8808-11ea-85cf-6bc017a3ce97.png)

![image](https://user-images.githubusercontent.com/64044709/80319471-3e9fd700-8808-11ea-90fb-9a56c12f6005.png)

![image](https://user-images.githubusercontent.com/64044709/80319479-4d868980-8808-11ea-8bac-b76ba85ec001.png)

**Comment by mayeaux** [comment]
Yeah it's on purpose, easier on the eyes and I don't mind that the white backgrounds stand out. Used to have a white background and the off colour grey is nicer imo.
