### ISSUE TITLE
Remove background from emoji images

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#275]
![Screen Shot 2020-04-30 at 5 50 04 PM](https://user-images.githubusercontent.com/7200471/80769621-10254300-8b0b-11ea-94a1-c497931d70c8.png)

This is what vid8's emojis look like right now, solution is to use some image processing and remove those white backgrounds from the images. Happy to accept a PR for this.

**Comment by mr-winson** [comment]
i just opened a pull for this
