### ISSUE TITLE
Saved video or audio progress when navigate away

### ISSUE THREAD

**Issue by mayeaux** [mayeaux/nodetube#331]
There is a really good event for when you navigate away.

Would be pretty easy to store it either on the mongo document or for a clean but somewhat unreliable solution you could do in the browser memory.

**Comment by BassOfBass** [comment]
By "browser memory" did you mean `localStorage`? It's pretty reliable and is better than storing unbounded arrays in the database. I doubt the people who clean their local storage regularly would be upset about the site not keeping track of them.

**Comment by mayeaux** [comment]
I ended up modelling the lastWatchedTime : models/LastWatchedTime.js and implementing it via the db. I like it that way so you can change devices easily without losing your spot, lmk what you think of the implementation.
