### ISSUE TITLE
increase file size?

### ISSUE THREAD

**Issue by chovy** [mayeaux/nodetube#36]
is there a file size limit I can increase? My vidoe wouldn't finish uploading.

**Comment by mayeaux** [comment]
The filesize limit is going to be defined on the User model. If you can change that database item value you can increase a limit.

**Comment by chovy** [comment]
Is there an admin account where I can add categories and such?

Anthony
http://profullstack.com

**Comment by mayeaux** [comment]
I just added some code where the first user will be created as an admin by default now. However if you check out the User model again you can see where you can change the role to `admin`
