### ISSUE TITLE
package.json "name" key doesn't conform (slightly) to the npm naming rules 

### ISSUE THREAD

**Issue by BassOfBass** [mayeaux/nodetube#362]
As per [npm docs](https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields):

> The "name" field contains your package’s name, and must be **lowercase** and one word, and may contain hyphens and underscores.

**Comment by mayeaux** [comment]
Well I wonder what their definition of 'must' is because so far I haven't ran into anything lol. Those docs look kind of sketchy to me, then again I don't mind renaming to nodetube

**Comment by BassOfBass** [comment]
_Sketchy_ docs on an official npm site?
VScode also throws a warning:
```
String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".
```

**Comment by mayeaux** [comment]
Yeah fair enough, I updated it now thanks for the heads up: https://github.com/mayeaux/nodetube/commit/c47f39b4038454ee04bb66a8ce5b16b9a4a621a4
