### ISSUE TITLE
HCaptcha / Recaptcha support

### ISSUE THREAD

**Issue by posix4e** [mayeaux/nodetube#37]
It would be super sweet if this had some ability to block bots. . What's cool is my site, hcaptcha.com allows you to make money while you block bots and is recaptcha compatible. Any interest for a patch?

**Comment by mayeaux** [comment]
The app actually supports Recaptcha out of the box, you just need to turn it on via a setting in .env.settings 

And then you can update the key in .env.private 

Have it turned off by default for obvious reasons. I'll check out your site though thanks for the comment!
