### ISSUE TITLE
Extensionless empty Stripe badge icons cause git to shit its pants during cloning/pulling

### ISSUE THREAD

**Issue by BassOfBass** [mayeaux/nodetube#383]
[These files](https://github.com/BassOfBass/nodetube/commit/89e31e6a3b85bfe1dc4902560a5d5118ce7239b9) specifically.

**Comment by mayeaux** [comment]
Thanks for the heads up

**Comment by BassOfBass** [comment]
Please accept the PR, I can't even review other PRs on my local machine because of this problem.
