### ISSUE TITLE
Create a Riot/Matrix room

### ISSUE THREAD

**Issue by DontUseGithub** [mayeaux/nodetube#39]
Many FOSS enthusiasts don't use Discord because it's proprietary. So we've got [Riot/Matrix](https://riot.im/app/) which is totally open source and decentralized. I'd recommend switching to it or at least creating a room there as well.
Cheers!

**Comment by mayeaux** [comment]
Thanks for the suggestion! Hadn't heard of them before but I just checked out their software and it's really nice. I created a room let me know if this link works for you: https://riot.im/app/#/room/!BApqKRDAmimeqEBHrn:matrix.org

Thanks!

**Comment by DontUseGithub** [comment]
You've set it to invites-only? Make it public.

**Comment by mayeaux** [comment]
Okay try this guy: https://riot.im/app/#/room/#nodetube:matrix.org

**Comment by DontUseGithub** [comment]
It works, thanks.
