### ISSUE TITLE
Thoughts on CI? 

### ISSUE THREAD

**Issue by gregg1494** [mayeaux/nodetube#44]
I always use Travis CI for my projects, easy to get up and running. I used it for my most recent Node project using Docker and AWS ELB.

**Comment by mayeaux** [comment]
I like CI, I haven't used a CI tool in a while though what would it take to setup Travis CI for this project? Thanks!

**Comment by gregg1494** [comment]
Linking the repo to travis on the travis CI website and creating a travis.yaml file in the root project dir is all you really need to get going.

**Comment by mayeaux** [comment]
Are you able to set any of that up for me? If you're able to do the things you can help with and then direct me on what else is needed to be done that would help a ton! :)

**Comment by gregg1494** [comment]
Ya I can set it up

**Comment by mayeaux** [comment]
Travis CI up and passing
