### ISSUE TITLE
While in full screen on chrome the mouse does not disappear.

### ISSUE THREAD

**Issue by mr-winson** [mayeaux/nodetube#54]
When I'm in full screen my mouse doesn't disappear, I am on a Mac, not sure if that matters or not?

**Comment by mayeaux** [comment]
I agree with you that after a set period of time the mouse disappearing is the best functionality. The frontend player for the videos we're using is called `plyr` if you google around I'm sure you can find their API for a mouse-timeout type of functionality. If you find the link to that API either your or me could update the code pretty quickly

**Comment by mr-winson** [comment]
Alright, I will do some research and if I find anything ill open a pull request!

**Comment by mayeaux** [comment]
Right on man good luck!

**Comment by mayeaux** [comment]
Also come join us in the Discord if you want that's where we're all working on stuff https://discord.gg/ejGah8H

**Comment by mr-winson** [comment]
Ok, I will found some info, ill fork to see if it works then ill push the request!

**Comment by mr-winson** [comment]
Is there any way you could tell me where the config file for plyr is?

**Comment by mayeaux** [comment]
For sure, check out: 

views/media.pug

and 

views/mediaPlayerPartials/plyrAndAutoplayFunctionalityJs

**Comment by mr-winson** [comment]
Thx

**Comment by mayeaux** [comment]
you'll find plyrOptions in the second file I think that's probably where you'll load it in

**Comment by mr-winson** [comment]
Yup I found it going to test it then I will open a pull!

**Comment by mr-winson** [comment]
Created the pull request

**Comment by mayeaux** [comment]
Is that implementation working locally for you? Like you tested it out and it seems to be working OK?

**Comment by mr-winson** [comment]
I'll test it with my Github Pages. I'll let you know

**Comment by mayeaux** [comment]
Best thing to do is set it up locally with your own instance of NodeTube. That way you can be 100% sure that it's working with the NodeTube setup, then I can check out your pull request locally and make sure it works and then accept your PR. That'd be my recommendation

**Comment by mr-winson** [comment]
Oh yeah, I just remembered that Github Pages is static. Ill do that

**Comment by mr-winson** [comment]
Alright, imma be honest, I'm following the directions in the README.MD file and some of the packages won't install. I don't know if it would be possible for you to run it.
If you want to test it then here is the edits needed:

Inside of: `views/mediaPlayerPartials/plyrAndAutoplayFunctionalityJs.pug`
Add a new line in between 43 and 44 and out `controlshidden: true,`

[Here](https://github.com/sampotts/plyr#standard-media-events) is the link to the documentation. [Here](https://github.com/sampotts/plyr/issues/579) is the link to a thread explaining it.
I'm not sure how to do the local instances so if you want to do that there is how.

Thanks,
Jude Wilson

**Comment by mayeaux** [comment]
Hey dude I'm super sorry because something stupid I pushed may have been messing you up! Can you try and pull the latest code and run `npm run installDeps` again?

**Comment by mayeaux** [comment]
And thanks a lot for your help! Definitely appreciated!

**Comment by mr-winson** [comment]
Yup!

**Comment by mr-winson** [comment]
I got all the way to the end and it's looking good. When I run npm start what exactly is supposed to happen after that? It did nothing. Not sure if I did something wrong or if I have another step?

**Comment by mayeaux** [comment]
Basically it should say somewhere in there something like `App is running at http://localhost:3000 in development mode`

Then if you go into your browser and go to localhost:3000 in the address bar you should see the app. Lmk if that works for you

**Comment by mr-winson** [comment]
ok

**Comment by Zerosez** [comment]
> When I'm in full screen my mouse doesn't disappear, I am on a Mac, not sure if that matters or not?
Should be fixed it's bouncing off my local stream right now.
#12 #25 #57 #3 #35 #8 #5 #58 #13 #16 

#15 #6 #33 #45 #51 #36 @mayeaux #23 #39

Going to be connecting the live tv networks which will be lived through the Facebook Audience instead of Netflix insights they get enough money through hosting all those trackers and seedy people over the years.

**Comment by mayeaux** [comment]
I'm super confused by this comment can you help me out?

**Comment by Zerosez** [comment]
But wait there's more.
Idk, mayes.io wasn't taken.
#61

**Comment by Ryochan7** [comment]
I would say the first task that should be done is to use a more recent version of Plyr. I found an old note in the Work Board about possibly updating Plyr to version 3.3.7 to have access to some additional features. I would hope that this issue is just a problem with the old player. I will try it on my end and see.

**Comment by mr-winson** [comment]
There was a boolean value that I am currently testing on my Mac to make the mouse disappear, if it works I'll tell all of you guys and make a pull request!
@Ryochan7 I noticed PLYR hasn't been updated in 2 or 3 years. If there is still a new version, how old is the version we are on right now?

**Comment by Ryochan7** [comment]
It looks like the latest version of Plyr is 3.5.6 and it was released on 2019/06/20. 2.0.16 was supposedly published around 2017/10/05. Anyway, I have tested version 3.3.7 and that version does hide the mouse cursor when the controls get hidden in fullscreen mode.

**Comment by mr-winson** [comment]
@Ryochan7 Ok cool, I must have been on wrong repository which is kinda scary. If you can get that up then I’ll remove my PR. I’m also having trouble running locally so that would be a huge help! Thx

**Comment by Ryochan7** [comment]
Tried the controlshidden change and it did not work out. I ended up choosing version 3.3.21 for an update. I have tested that version previously and it does not suffer from setting the hidden attr on tags where they should not exist (for mute and volume controls) like 3.3.7 does.

**Comment by mayeaux** [comment]
@mr-winson you still need help getting an instance up? And thanks to Ryochan the latest code on .live should be working as you were hoping for @mr-winson so I'm gonna close this issue thanks @Ryochan7 !
